!!org.paint.config.PaintConfig
bpPaintColor: !color '138, 190, 204, 255'
ccPaintColor: !color '138, 204, 177, 255'
collapse_no_exp: true
curatedPaintColor: !color '255, 204, 0, 255'
expPaintColor: !color '61, 153, 61, 255'
full_msa: false
gafdir: /Users/suzi/projects/go/gene-associations/submission/paint/PTHR10003/
inferPaintColor: !color '61, 100, 153, 255'
mfPaintColor: !color '177, 204, 138, 255'
msa_colors:
- !color '51, 102, 77, 255'
- !color '112, 153, 92, 255'
- !color '204, 194, 143, 255'
msa_threshold:
- 80.0
- 60.0
- 40.0
msa_weighted_colors:
- !color '21, 138, 255, 255'
- !color '220, 233, 255, 255'
msa_weighted_threshold:
- 90.0
- 75.0
tree_distance_scaling: 50.0
treedir: /Users/suzi/projects/go/data/trees/panther/
use_distances: true
weighted: true
